obj-$(CONFIG_SOC_DUMP)	+= socdump.o
obj-$(CONFIG_PMIC_POWER_DUMP)	+= pmic_power.o
obj-$(CONFIG_PMIC_GPIO_DUMP)	+= pmic_gpio.o
obj-$(CONFIG_PMIC_LED_LCD_DUMP)	+= pmic_led_lcd.o
obj-$(CONFIG_PMIC_LED_LCD_DUMP)	+= pmic_rtc.o
obj-$(CONFIG_PMIC_BATT_DUMP)	+= pmic_batt.o
obj-$(CONFIG_MSIC_DUMP)		+= msic.o
obj-$(CONFIG_SOC_DUMP_TEST_2)	+= dr_test2.o
